spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: gestionPaqSer
          uri: lb://gestionPaqSer
          predicates:
            - Path=/api/services/**
          filters:
            - StripPrefix=2
        - id: gestionCompra
          uri: lb://gestionCompra
          predicates:
            - Path=/api/compras/**
          filters:
            - StripPrefix=2
        - id: gestionEmpCli
          uri: lb://gestionEmpCli
          predicates:
            - Path=/api/usuarios/**
          filters:
            - StripPrefix=2
        - id: servicioOauth
          uri: lb://servicioOauth
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2
        - id: gestionEmail
          uri: lb://gestionEmail
          predicates:
            - Path=/api/emails/**
          filters:
            - StripPrefix=2
management:
  endpoints:
    web:
      exposure:
        include: "*"